package mymusic2;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mymusic2.Controller.AddController;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cuong
 */
public class NewCategory extends javax.swing.JFrame {

    /**
     * Creates new form NewSong
     */
    public NewCategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newCategory_theLoaiLabel = new javax.swing.JLabel();
        newCategory_theLoaiTextField = new javax.swing.JTextField();
        newCategory_okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("New Category");

        newCategory_theLoaiLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newCategory_theLoaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newCategory_theLoaiLabel.setText("Thể loại :");

        newCategory_theLoaiTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newCategory_okButton.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newCategory_okButton.setText("OK");
        newCategory_okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCategory_okButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(newCategory_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(newCategory_theLoaiLabel)
                .addGap(28, 28, 28)
                .addComponent(newCategory_theLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCategory_theLoaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCategory_theLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(newCategory_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newCategory_okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCategory_okButtonMouseClicked
        if(newCategory_theLoaiTextField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
        }
        else{
            try {
                boolean tmp= AddController.addCategory(newCategory_theLoaiTextField.getText());
                if(tmp) JOptionPane.showMessageDialog(this, "ok !!");
                else JOptionPane.showMessageDialog(this, "Thể loại này đã tồn tại !!");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(NewCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_newCategory_okButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newCategory_okButton;
    private javax.swing.JLabel newCategory_theLoaiLabel;
    private javax.swing.JTextField newCategory_theLoaiTextField;
    // End of variables declaration//GEN-END:variables
}
