package mymusic2;

import java.io.File;
import java.io.FileFilter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mymusic2.Controller.AddController;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cuong
 */
public class NewSong extends javax.swing.JFrame {

    /**
     * Creates new form NewSong
     */
    public NewSong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        newSong_tenbaihatLabel = new javax.swing.JLabel();
        newSong_caSiLabel = new javax.swing.JLabel();
        newSong_tacGiaLabel = new javax.swing.JLabel();
        newSong_ngayPhatHanhLabel = new javax.swing.JLabel();
        newSong_theLoaiLabel = new javax.swing.JLabel();
        newSong_tenBaiHatTextField = new javax.swing.JTextField();
        newSong_caSiTextField = new javax.swing.JTextField();
        newSong_tacGiaTextField = new javax.swing.JTextField();
        newSong_ngayPhatHanhTextField = new javax.swing.JTextField();
        newSong_theLoaiTextField = new javax.swing.JTextField();
        newSong_okButton = new javax.swing.JButton();
        new_singer = new javax.swing.JButton();
        new_author = new javax.swing.JButton();
        new_category = new javax.swing.JButton();
        urlLabel = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("New Song");

        newSong_tenbaihatLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_tenbaihatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newSong_tenbaihatLabel.setText("Tên bài hát :");

        newSong_caSiLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_caSiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newSong_caSiLabel.setText("ID ca sĩ :");

        newSong_tacGiaLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_tacGiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newSong_tacGiaLabel.setText("ID tác giả :");

        newSong_ngayPhatHanhLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_ngayPhatHanhLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newSong_ngayPhatHanhLabel.setText("Ngày phát hành :");

        newSong_theLoaiLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_theLoaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newSong_theLoaiLabel.setText("ID thể loại :");

        newSong_tenBaiHatTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newSong_caSiTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newSong_tacGiaTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newSong_ngayPhatHanhTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newSong_theLoaiTextField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        newSong_okButton.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        newSong_okButton.setText("OK");
        newSong_okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newSong_okButtonMouseClicked(evt);
            }
        });

        new_singer.setText("New");
        new_singer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_singerMouseClicked(evt);
            }
        });

        new_author.setText("New");
        new_author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_authorMouseClicked(evt);
            }
        });

        new_category.setText("New");
        new_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_categoryMouseClicked(evt);
            }
        });

        urlLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        urlLabel.setText("URL :");

        browseButton.setText("Browse");
        browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newSong_caSiLabel)
                                    .addComponent(newSong_tacGiaLabel)
                                    .addComponent(newSong_tenbaihatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newSong_tenBaiHatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(newSong_tacGiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newSong_caSiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(new_singer)
                                            .addComponent(new_author)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newSong_ngayPhatHanhLabel)
                                    .addComponent(newSong_theLoaiLabel)
                                    .addComponent(urlLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(browseButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(newSong_ngayPhatHanhTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(newSong_theLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(new_category)))))))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(newSong_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSong_tenbaihatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSong_tenBaiHatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSong_caSiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSong_caSiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_singer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSong_tacGiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSong_tacGiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_author))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSong_ngayPhatHanhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSong_ngayPhatHanhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSong_theLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSong_theLoaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_category))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(newSong_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newSong_okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSong_okButtonMouseClicked
        if(newSong_tenBaiHatTextField.getText().equals("")
            || newSong_caSiTextField.getText().equals("")
            || newSong_tacGiaTextField.getText().equals("")
            || newSong_ngayPhatHanhTextField.getText().equals("")
            || newSong_theLoaiTextField.getText().equals("")
            || urlTextField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
        }
        else{
            try {
                boolean tmp= AddController.addSong(newSong_tenBaiHatTextField.getText(), Integer.parseInt(newSong_caSiTextField.getText()), Integer.parseInt(newSong_tacGiaTextField.getText()), newSong_ngayPhatHanhTextField.getText(), Integer.parseInt(newSong_theLoaiTextField.getText()), urlTextField.getText());
                if(tmp) JOptionPane.showMessageDialog(this, "ok !!");
                else JOptionPane.showMessageDialog(this, "Bài hát đã tồn tại !!");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(NewSong.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_newSong_okButtonMouseClicked

    private void new_singerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_singerMouseClicked
        new NewSinger().setVisible(true);
    }//GEN-LAST:event_new_singerMouseClicked

    private void new_authorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_authorMouseClicked
        new NewAuthor().setVisible(true);
    }//GEN-LAST:event_new_authorMouseClicked

    private void new_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_categoryMouseClicked
        new NewCategory().setVisible(true);
    }//GEN-LAST:event_new_categoryMouseClicked

    private void browseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMouseClicked
        JFileChooser choose= new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("mp3 file", "mp3");
        choose.setFileFilter(filter);
        choose.setMultiSelectionEnabled(false);
        
        int action= choose.showOpenDialog(this);
        if(action == JFileChooser.APPROVE_OPTION){
            File file= choose.getSelectedFile();
            urlTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel newSong_caSiLabel;
    private javax.swing.JTextField newSong_caSiTextField;
    private javax.swing.JLabel newSong_ngayPhatHanhLabel;
    private javax.swing.JTextField newSong_ngayPhatHanhTextField;
    private javax.swing.JButton newSong_okButton;
    private javax.swing.JLabel newSong_tacGiaLabel;
    private javax.swing.JTextField newSong_tacGiaTextField;
    private javax.swing.JTextField newSong_tenBaiHatTextField;
    private javax.swing.JLabel newSong_tenbaihatLabel;
    private javax.swing.JLabel newSong_theLoaiLabel;
    private javax.swing.JTextField newSong_theLoaiTextField;
    private javax.swing.JButton new_author;
    private javax.swing.JButton new_category;
    private javax.swing.JButton new_singer;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
